server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
#  cloud:
#    gateway:
#      routes:
##        - id: employeeModule
##          uri: lb://FIRST-SERVICE
##          predicates:
##            - Path=/employee/**
##          filters:
##            - name: CircuitBreaker
##              args:
##                name: fallbackCommand
##                fallbackUri: forward:/fallback/first
#        - id: consumerModule
#          uri: lb://SECOND-SERVICE
#          predicates:
#            - Path=/consumer/**
#
#        - id: employeeModule
#          uri: lb://FIRST-SERVICE
#          predicates:
#            - Path=/employee/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: fallbackCommand
#                fallbackUri: forward:/fallback/first
#
#        - id: checkEditedContractModule
#          uri: lb://CONTRACT-CHECK-EDITED-TEST-LOCAL
#          predicates:
#            - Path=/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG