spring:
  application:
    name: eureka-discovery-service

server:
  port: 8083
eureka:
#  server:
#    expected-client-renewal-interval-seconds: 1
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8083/eureka